/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */

import React, { useState , useEffect } from 'react';
import Head from "next/head";
import Image from "next/image";
import LanguageSwitcher from "./components/LanguageSwitcher";
import { Menu, MenuButton, MenuItem, MenuItems } from '@headlessui/react';
import ProgressBar from './components/ProgressBar.js';
import MyProject from './components/Myproject.js';
import  db from '/data/db.json';
import { useTranslation } from 'react-i18next';
import ThemeToggle from './components/ThemeToggle';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

export async function getServerSideProps({ locale }) {
  console.log(locale)
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])), 
      
    },
  };
}

export default function Home() {

  const [activeTab, setActiveTab] = useState("experience");
  const [language, setLanguage] = useState("en"); 
  const { t } = useTranslation("common");
  const [backgroundImage, setBackgroundImage] = useState("");
  const [isRtl, setIsRtl] = useState(false);

  useEffect(() => {
    const updateBackground = () => {
      if (window.innerWidth >= 1024) {
        setBackgroundImage("url('img/back8.jpg')");
      } else {
        setBackgroundImage(""); 
      }
    };
    if (typeof document !== "undefined") {
      setIsRtl(document.documentElement.dir === "rtl");
    }
    updateBackground();
    window.addEventListener("resize", updateBackground);
    return () => {
      window.removeEventListener("resize", updateBackground);
    };
  }, []);

 
  return (
    <>
      <Head>
        <title>portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
           rel="preload"
           href="/fonts/IRANRounded/IRAN-Rounded.woff"
           as="font"
           type="font/woff"
           crossOrigin="anonymous"
         />
      </Head>
      <main className="flex flex-col items-center dark:bg-gray-900 dark:text-white">
        <div  style={{
           backgroundImage,
           }} className="bg-fixed bg-cover bg-no-repeat relative h-full w-full rtl:bg-right">
        <div className=" z-10 sticky flex items-center justify-between w-full backdrop-contrast-50 lg:p-2 p-0 bg-gray-100 dark:bg-gray-800  shadow-lg">
         <div className="flex items-center lg:space-x-4 space-x-2 rtl:space-x-reverse">
           <p className="lg:text-lg text-base text-slate-600 dark:text-slate-200 rtl:text-right ml-2 rtl:mr-2 rtl:font-IRANRounded">
            {t("maryam alipour")}
           </p>
           <LanguageSwitcher/>
         </div>
          <div className="flex items-center  lg:space-x-4 space-x-0 rtl:space-x-reverse">
          <ThemeToggle/>
          <div className="lg:hidden relative flex justify-center mx-0 pr-2 rtl:pl-2">
           <Menu>
            <MenuButton className="text-slate-600 dark:text-slate-100">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
              <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
              </svg>
            </MenuButton>
            <MenuItems
             anchor="bottom"
             className="absolute z-50 bg-white dark:bg-gray-900 top-full mt-2 w-40 shadow-lg rounded-md"
             style={{
              left: isRtl ? '0' : 'auto',
              right: !isRtl ? '0' : 'auto',
              }}
            >
           <MenuItem>
            <a className="block px-4 py-2 data-[focus]:bg-blue-100 dark:data-[focus]:bg-blue-700 rtl:text-left rtl:font-IRANRounded text-xs" href="#experience">
              {t("Experience")}
            </a>
           </MenuItem>
           <MenuItem>
            <a className="block px-4 py-2 data-[focus]:bg-blue-100 dark:data-[focus]:bg-blue-700 rtl:text-left rtl:font-IRANRounded text-xs" href="#Skills">
              {t("Skills")}
            </a>
           </MenuItem>
           <MenuItem>
            <a className="block px-4 py-2 data-[focus]:bg-blue-100 dark:data-[focus]:bg-blue-700 rtl:text-left rtl:font-IRANRounded text-xs" href="#projects">
              {t("Projects")}
            </a>
            </MenuItem>
            </MenuItems>
           </Menu>
          </div>
          <div className="lg:flex justify-between hidden  ">
       
           <div className="mr-5 rtl:ml-5">
            <a
              href="#experience"
              className="flex items-center"
            >
              <h1 className="text-slate-600 rtl:text-left rtl:font-IRANRounded">{t("Experience")}</h1>
            </a>
          </div>
          <div className="mr-5 rtl:ml-5">
            <a
              href="#Skills"
              className="flex items-center"
            >
              <h1 className="text-slate-600 rtl:text-left rtl:font-IRANRounded">{t("Skills")}</h1>
            </a>
          </div>
          <div className="mr-5 rtl:ml-5">
            <a
              href="#Projects"
              className="flex items-center"
            >
              <h1 className="text-slate-600 rtl:text-left rtl:font-IRANRounded ">{t("Projects")}</h1>
            </a>
          </div>
          </div>
          </div>
         </div>
            <div className="flex flex-row items-center justify-center  lg:w-full w-11/12 py-16 dark:bg-gray-900 dark:text-white rtl:text-right">
              <div className="flex flex-col items-start  ml-5 rtl:mr-5">
              <h3 className="mb-3 lg:text-xl text-lg font-bold rtl:text-right rtl:font-IRANRounded">{t("I am")}</h3>
              <h1 className="lg:text-7xl text-xl  mb-3 font-bold rtl:text-right rtl:font-IRANRounded rtl:mb-6">{t("Maryam Alipour")}</h1>
              <h2 className="lg:text-4xl text-xl font-medium animate-pulse rtl:text-right rtl:font-IRANRounded mb-3 ">{t("Front End Developer")}</h2>
              <h2 className="lg:text-4xl text-xl font-medium animate-pulse rtl:text-right rtl:font-IRANRounded ">{t("Software engineer")}</h2>
              <div className="flex mt-3">
               <a href="/Maryam Alipour_1403-9-5-1-1.pdf" 
                 target="_blank" 
                 rel="noopener noreferrer" 
                 className="bg-gradient-to-r from-[#eca348] to-[#ee9324] p-4 rounded-lg text-white lg:text-xl text-xs ease-in duration-300 rtl:text-left  rtl:font-IRANRounded">{t("Download CV")}</a>
              </div>
              </div>
              <div className="w-full max-w-[580px]  ">
                <Image
                  src="/img/ax111.png"
                  alt="My Image"
                  layout="responsive"
                  width={480}
                  height={480}
                  priority
                />
              </div>
            </div>
        
        </div>
     {/* <div className="bg-slate-100 w-full flex flex-col items-center mb-10">
       <div className="grid grid-cols-2 place-content-between w-7/12 my-5">
         <h1 className="text-5xl">My Servises</h1>
         <div className="justify-self-end"><a className="bg-[#eca348] p-4 rounded-lg text-white flex justify-center text-xl">Hire Me</a></div>
        </div>
        /*<div className="grid grid-cols-1 gap-8 w-full max-w-7xl sm:grid-cols-2">

          <div className="p-12 bg-white rounded-lg shadow hover:shadow-lg transition-shadow flex items-center">
            <div style={{backgroundImage: `url('img/Untitled.jpg')`}} className="mr-10 bg-no-repeat rounded-full">
             <svg xmlns="http://www.w3.org/2000/svg" className="h-14 w-14" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />
             </svg>
            </div>
            <div>
            <h2 className="mb-3 text-2xl font-bold">Creative Design</h2>
            <span className="text-[#286eb4] text-xl">Start from $199</span>
            <p className="text-gray-700 mt-3">
            Stet lorem dolor diam amet vero eos. No stet est diam amet diam ipsum. Clita dolor duo clita sit sed sit dolor eos..
            </p>
            </div> 
           
          </div>

          <div className="p-12 bg-white rounded-lg shadow hover:shadow-lg transition-shadow flex items-center">
          <div style={{backgroundImage: `url('img/Untitled.jpg')`}} className="mr-10 bg-no-repeat rounded-full">
           <svg xmlns="http://www.w3.org/2000/svg" className="h-14 w-14" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
           </svg>
           </div>  
           <div>
            <h2 className="mb-3 text-2xl font-bold">Web Design</h2>
            <span className="text-[#286eb4] text-xl">Start from $199</span>
            <p className="text-gray-700 mt-3">
            Stet lorem dolor diam amet vero eos. No stet est diam amet diam ipsum. Clita dolor duo clita sit sed sit dolor eos.
            </p>
           </div>
          </div>

          <div className="p-12 bg-white rounded-lg shadow hover:shadow-lg transition-shadow flex items-center">
          <div style={{backgroundImage: `url('img/Untitled.jpg')`}} className="mr-10 bg-no-repeat rounded-full">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-14 w-14" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
             <path strokeLinecap="round" strokeLinejoin="round" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
            </svg>
           </div> 
           <div>
            <h2 className="mb-3 text-2xl font-bold">UI/UX Design</h2>
            <span className="text-[#286eb4] text-xl">Start from $199</span>
            <p className="text-gray-700 mt-3">
            Stet lorem dolor diam amet vero eos. No stet est diam amet diam ipsum. Clita dolor duo clita sit sed sit dolor eos.
            </p>
           </div> 
          </div>

          <div className="p-12 bg-white rounded-lg shadow hover:shadow-lg transition-shadow flex items-center">
          <div style={{backgroundImage: `url('img/Untitled.jpg')`}} className="mr-10 bg-no-repeat rounded-full">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-14 w-14" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
             <path strokeLinecap="round" strokeLinejoin="round" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
           </div>
           <div> 
            <h2 className="mb-3 text-2xl font-bold">Graphic Design</h2>
            <span className="text-[#286eb4] text-xl">Start from $199</span>
            <p className="text-gray-700 mt-3">
            Stet lorem dolor diam amet vero eos. No stet est diam amet diam ipsum. Clita dolor duo clita sit sed sit dolor eos.
            </p>
           </div> 
          </div>
        </div>
      </div> */}
      <div className='lg:w-2/3 w-11/12 my-16 bg-gradient-to-r from-[#dbf7fa] via-[#61bbef] to-[#3f94ca] shadow-2xl shadow-[#0b2057] rounded-xl lg:p-20 p-5'>
        <span className='lg:text-2xl text-xl mb-7'>{t("About Me")}</span>
        <p className='lg:text-xl text-lg text-justify'>{t("My name is Maryam Alipour, a software engineer specializing in front-end development with a passion for learning computer sciences. Currently, I am available for remote work or project-based opportunities, and I can be present in Tehran for essential tasks or project deliveries. Alongside my technical expertise, I prioritize developing business skills, self-awareness, and understanding personality types to continually grow both professionally and personally.")}</p>
      </div>


      <div className="flex  flex-col lg:flex-row lg:justify-around justify-center lg:w-2/3 w-11/12 my-10">
        <div className=" basis-full lg:basis-2/4 rtl:ml-10 ">
          <h1 id='experience' className="lg:text-5xl text-2xl mb-12 rtl:text-center rtl:font-IRANRounded">{t("Skills & Experience")}</h1>
          <h3 id='Skills' className="lg:text-3xl text-xl rtl:text-right rtl:font-IRANRounded">{t("My Skills")}</h3>
          <div className="grid grid-cols-2 gap-4 mt-5">
          <div className="flex w-full flex-col gap-4">
            <div className="flex items-center justify-between">
              <h6 className="lg:text-base text-xs">SQL</h6>
              <span className="text-xs lg:text-base">50%</span>
            </div>
            <ProgressBar value={50} color="#8A2BE2" />

            <div className="flex items-center justify-between">
              <h6 className="lg:text-base text-xs">TypeScript</h6>
              <span className="text-xs lg:text-base">50%</span>
            </div>
            <ProgressBar value={50} color="#FFA500" />

            <div className="flex items-center justify-between">
              <h6 className="lg:text-base text-xs">JavaScript</h6>
              <span className="text-xs lg:text-base">90%</span>
            </div>
            <ProgressBar value={90} color="#0000FF" />
          </div>
          <div className="flex w-full flex-col gap-4">
            <div className="flex items-center justify-between">
              <h6 className="lg:text-base text-xs">TailwindCSS</h6>
              <span className="text-xs lg:text-base">85%</span>
            </div>
            <ProgressBar value={85} color="#286eb4" />

            <div className="flex items-center justify-between">
              <h6 className="lg:text-base text-xs">Next.js</h6>
              <span className="text-xs lg:text-base">65%</span>
            </div>
            <ProgressBar value={65} color="black" />

            <div className="flex items-center justify-between">
              <h6 className="lg:text-base text-xs">React.js</h6>
              <span className="text-xs lg:text-base">90%</span>
            </div>
            <ProgressBar value={90} color="#DC143C" />
          </div>
          </div>
        </div>
        <div className="lg:ml-10 basis-full w-11/12  lg:w-1/2 lg:basis-2/4 mx-0 mt-8 lg:mt-0 ">
          <div className="grid grid-cols-2 place-content-stretch border-[#eca348] border-2 rounded-lg w-full ">
            <button
               className={`rtl:text-center rtl:font-IRANRounded lg:text-2xl text-lg py-4 ${activeTab === 'experience' ? 'bg-gradient-to-r from-[#eca348] to-[#ee9324] ' : ''}`}
               onClick={() => setActiveTab("experience")}
             >
               {t("Experience")}
             </button>
             <button
               className={`rtl:text-center rtl:font-IRANRounded lg:text-2xl text-lg py-4 ${activeTab === 'education' ? 'bg-gradient-to-r from-[#eca348] to-[#ee9324]' : ''}`}
               onClick={() => setActiveTab("education")}
             >
               {t("Education")}
             </button>
          </div>

           {activeTab === 'experience' && (
             <div className='grid grid-cols-2 gap-4 mt-5 pl-5'>
               <div className='grid gap-y-5'>
                 <div className='mb-5 rtl:mr-5'>
                 <h5 className='lg:text-2xl text-sm rtl:text-right rtl:font-IRANRounded'>{t("Front End Developer")}</h5>
                 <hr className='my-2 text-current'></hr>
                 <p className='lg:text-lg text-xs text-[#286eb4] rtl:text-right'>{t("2022 2024")}</p>
                 <h6 className='lg:text-xl text-sm rtl:text-right rtl:font-IRANRounded'>Karjoo.plus</h6>
                 </div>
                 <div className='rtl:mr-5'>
                 <h5 className='lg:text-2xl text-sm rtl:text-right rtl:font-IRANRounded'>{t("Insurance employee")}</h5>
                 <hr className='my-2 text-current'></hr>
                 <p className='lg:text-lg text-xs text-[#286eb4] rtl:text-right'>{t("2020 2022")}</p>
                 <h6 className='lg:text-xl text-sm rtl:text-right rtl:font-IRANRounded'>{t("Iran Insurance Office")}</h6>
                 </div>
               </div>
               <div className='grid gap-y-5 rtl:mr-5'>
               <div className='mb-5'>
                 <h5 className='lg:text-2xl text-sm rtl:text-right rtl:font-IRANRounded'>{t("WordPress website")}</h5>
                 <hr className='my-2 text-current'></hr>
                 <p className='lg:text-lg text-xs text-[#286eb4] rtl:text-right'>{t("2018 2020")}</p>
                 <h6 className='lg:text-xl text-sm rtl:text-right rtl:font-IRANRounded'>{t("Personal business")}</h6>
                 </div>
             <div>
                 <h5 className='lg:text-2xl text-sm rtl:text-right rtl:font-IRANRounded'>{t("Training Manager")}</h5>
                 <hr className='my-2 text-current w-1/2'></hr>
                 <p className='lg:text-lg text-xs text-[#286eb4] rtl:text-right'>{t("2007 2010")}</p>
                 <h6 className='lg:text-xl text-sm rtl:text-right rtl:font-IRANRounded'>{t("Ishraq School of Zanjan")}</h6>
                 </div>
               </div>
             </div>
           )}

           {activeTab === 'education' && (
            <div className='grid grid-cols-2 gap-4 mt-5 pl-5'>
              <div className='grid gap-y-5'>
                <h2 className='lg:text-2xl text-sm rtl:mr-5 rtl:font-IRANRounded'>{t("Software Engineering, North University")}</h2>
                <a href='https://www.freecodecamp.org/certification/fcc7f968b53-fdcb-4867-8250-f6686f422f81/front-end-development-libraries'><h2 className='text-cyan-400 lg:text-2xl text-sm rtl:mr-5'>{t("Freecodecamp Front End Development")}</h2></a>
                <h2 className='lg:text-2xl text-sm rtl:mr-5 rtl:font-IRANRounded'>{t("Sabzlearn Javascript")}</h2>
                <h2 className='lg:text-2xl text-sm rtl:mr-5 rtl:font-IRANRounded'>{t("Sabzlearn Reactjs")}</h2>
              </div>
             {/* <div className='grid gap-y-5'>
                <h2 className='text-2xl'>IOS Development</h2>
                <h2 className='text-2xl'>Cambridge University</h2>
                <h2 className='text-2xl'>Apps Design</h2>
                <h2 className='text-2xl'>Cambridge University</h2>
              </div>*/}
            </div>
           )}
        </div>
      </div>


      <div id='Projects' className='my-10 lg:w-2/3 w-11/12'>
          <h1 className='lg:text-5xl text-xl mb-10 rtl:text-right rtl:font-IRANRounded ml-9 lg:ml-0 rtl:mr-9'>{t("My Projects")}</h1>
          <div className='grid grid-cols-2 lg:grid-cols-3 gap-5'>
            {db.projects.map((project) => (
               <MyProject key={project.id} {...project}/>
             ))
            }
          </div>
      </div>
      <div className=' w-full flex justify-center'>
       <div className='grid grid-cols lg:w-1/2 w-full py-24 lg:py-32 ml-9 lg:ml-0 rtl:mr-9'>
        <div className='py-10'>
          <h1 className='lg:text-5xl text-xl rtl:text-right rtl:font-IRANRounded'>{t("Let's Work Together")}</h1>
          <div className='mt-16'>
            <p className='lg:text-xl text-lg text-slate-500 mb-5 rtl:text-right rtl:font-IRANRounded'>{t("Call me:")}</p>
            <h3 className='lg:text-3xl text-lg'>09193429924</h3>
            <hr></hr>
          </div>
          <div className='mt-16'>
            <p className='lg:text-xl text-lg text-slate-500 mb-5 rtl:text-right rtl:font-IRANRounded'>{t("Mail me:")}</p>
            <h3 className='lg:text-3xl text-lg'>maryamalipour1901@gmail.com</h3>
            <hr></hr>
          </div>
         <div className='mt-16'>
          <p className='text-xl text-slate-500 mb-7 rtl:font-IRANRounded'>Follow me:</p>
          <div className='flex'>
           <div className='bg-gradient-to-r via-40% via-[#f1d4ad] from-[#eca348] to-[#ee9324] rounded-lg shadow-lg shadow-slate-700 ring-2 ring-[#f5ad55] w-12 h-12 flex justify-center items-center mr-4'>
           <a href='https://github.com/maryaaama' target="_blank" rel="noopener noreferrer">
           <img src='/img/github.png'/>
           </a>
           </div>
           <div className='bg-gradient-to-r via-40% via-[#f1d4ad] from-[#eca348] to-[#f0890b] rounded-lg shadow-lg shadow-slate-700 ring-2 ring-[#f5ad55] w-12 h-12 flex justify-center items-center mr-4'>
           <a href='https://wa.me/9193429924?text=Hey%there%How’re%you%doing'target="_blank" rel="noopener noreferrer" >
           <img src='/img/whatsapp.png'/>
           </a>
           </div>
           <div className='bg-gradient-to-r via-40% via-[#f1d4ad] from-[#eca348] to-[#f0890b] rounded-lg shadow-lg shadow-slate-700 ring-2 ring-[#f5ad55] w-12 h-12 flex justify-center items-center mr-4'>
           <a href='https://www.linkedin.com/in/maryaaam-alipour-43a0a022b' target="_blank" rel="noopener noreferrer">
          <img src='/img/linkdin.png'/>
           </a>
           </div>
           <div className='bg-gradient-to-r via-40% via-[#f1d4ad] from-[#eca348] to-[#f0890b] rounded-lg shadow-lg shadow-slate-700 ring-2 ring-[#f5ad55] bg-blend-darken w-12 h-12 flex justify-center items-center mr-4'>
           <a href='https://t.me/maryaaamalipour' target="_blank" rel="noopener noreferrer">
           <img src='/img/telegram.png'/>
           </a>
           </div> 
          </div>
         </div>
        </div>
       {/*<div><ContactUs/></div>*/} 
       </div>
      </div>
      </main>
      
    </>
  );
}
